#!/usr/bin/env bash

rm -rf "$@"/home/web
cp -r static-site "$@"/home/web
cp static-site/index.hoon "$@"/home/web.hoon
rm -rf "$@"/home/ren/partials
cp -r partials "$@"/home/ren/partials
cp urb.hoon "$@"/home/ren
exit
